[workspace]

members = [
    "examples/routing-plugin", "integration/rust",
    "pgdog",
    "pgdog-plugin",
    "plugins/pgdog-routing",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
debug = true
