# Basic users configuration.
#
# Two users:
#
# - pgdog: in transaction mode, default settings
# - pgdog_session: in session mode, other settings are default
#
[[users]]
name = "pgdog"
database = "pgdog"
password = "pgdog"
replication_mode = true

[[users]]
name = "pgdog_replication"
database = "pgdog"
password = "pgdog"
server_user = "pgdog"
replication_mode = true
min_pool_size = 0

[[users]]
name = "pgdog_session"
database = "pgdog"
password = "pgdog"
server_user = "pgdog"
pooler_mode = "session"
min_pool_size = 0

[[users]]
name = "pgdog"
database = "pgdog_sharded"
password = "pgdog"
