# Basic users configuration.
#
# Two users:
#
# - pgdog: in transaction mode, default settings
# - pgdog_session: in session mode, other settings are default
#
[[users]]
name = "pgdog"
database = "pgdog"
password = "pgdog"

[[users]]
name = "pgdog_session"
database = "pgdog"
password = "pgdog"
server_user = "pgdog"
pooler_mode = "session"

[[users]]
name = "pgdog"
database = "pgdog_sharded"
password = "pgdog"
# min_pool_size = 0
