[general]
query_timeout = 1_000
checkout_timeout = 1_000
connect_timeout = 1_000
load_balancing_strategy = "round_robin"
rollback_timeout = 1_000
read_write_strategy = "aggressive"

[[databases]]
name = "pgdog"
host = "127.0.0.1"

[[databases]]
name = "pgdog"
host = "127.0.0.1"
role = "replica"
read_only = true

[[databases]]
name = "pgdog_sharded"
host = "127.0.0.1"
database_name = "shard_0"
shard = 0

[[databases]]
name = "pgdog_sharded"
host = "127.0.0.1"
database_name = "shard_1"
shard = 1

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5435
role = "primary"
database_name = "pgdog"

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5436
role = "replica"
database_name = "pgdog"
read_only = true

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5437
role = "replica"
database_name = "pgdog"
read_only = true

[[databases]]
name = "failover"
host = "127.0.0.1"
port = 5438
role = "replica"
database_name = "pgdog"
read_only = true

[[sharded_tables]]
database = "pgdog_sharded"
name = "sharded"
column = "id"
data_type = "bigint"
primary = true

[[sharded_tables]]
database = "pgdog_sharded"
column = "customer_id"
data_type = "bigint"

[[omnisharded_tables]]
database = "pgdog_sharded"
tables = ["sharded_omni"]

[admin]
password = "pgdog"


#
# ActiveRecord sends these queries
# at startup to figure out the schema.
#
# This will route them to only one shard instead of issuing
# cross-shard queries and getting incorrect results.
#
[[manual_queries]]
fingerprint = "e78fe2c08de5f079" #[16685804461073231993]

[[manual_queries]]
fingerprint = "43258d068030bb3e" #[4838428433739463486]

[[manual_queries]]
fingerprint = "08aab2cee482a97d" #[624508100011010429]

[[manual_queries]]
fingerprint = "23cd60d5972d1712" #[2579824632033777426]

[[manual_queries]]
fingerprint = "bb38525ebeb46656" #[13490623250668217942]

[[manual_queries]]
fingerprint = "f4814b6fadabc4c1" #[17618446160277259457]

[[manual_queries]]
fingerprint = "04dc05f480b702d3"

[[manual_queries]]
fingerprint = "2d9944fc9caeaadd" # [3285733254894627549]
