[[users]]
name = "pgdog"
database = "pgdog"
password = "pgdog"

[[users]]
name = "pgdog"
database = "pgdog_sharded"
password = "pgdog"

[[users]]
name = "pgdog"
database = "failover"
password = "pgdog"
