name: ci
on:
  push:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install CMake 3.31
        run: |
          sudo apt remove cmake
          sudo pip3 install cmake==3.31.6
          cmake --version
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install CMake 3.31
        run: |
          sudo apt remove cmake
          sudo pip3 install cmake==3.31.6
          cmake --version
      - name: Build
        run: cargo build
      - name: Check release
        run: cargo check --release
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1" # Change this when updating tooling
      - name: Setup PostgreSQL
        run: |
          sudo service postgresql start
          sudo -u postgres createuser --superuser --login $USER
          sudo -u postgres createdb $USER
          bash integration/setup.sh
          sudo apt update && sudo apt install -y python3-virtualenv
          sudo gem install bundler
          sudo apt remove -y cmake
          sudo pip3 install cmake==3.31.6
          cmake --version
          cargo install cargo-nextest --version "0.9.78" --locked
          bash integration/toxi/setup.sh
      - name: Install test dependencies
        run: cargo install cargo-nextest --version "0.9.78" --locked
      - name: Run tests
        run: cargo nextest run -E 'package(pgdog)' --no-fail-fast --test-threads=1
      - name: Run documentation tests
        run: cargo test --doc
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: release-1
      - name: Setup dependencies
        run: |
          sudo service postgresql start
          sudo -u postgres createuser --superuser --login $USER
          sudo -u postgres createdb $USER
          bash integration/setup.sh
          sudo apt update && sudo apt install -y python3-virtualenv
          sudo gem install bundler
          sudo apt remove -y cmake
          sudo pip3 install cmake==3.31.6
          cmake --version
          cargo install cargo-nextest --version "0.9.78" --locked
          bash integration/toxi/setup.sh
      - name: Build PgDog
        run: cargo build --release
      - name: pgbench
        run: bash integration/pgbench/run.sh
      - name: Go
        run: bash integration/go/run.sh
      - name: JavaScript
        run: bash integration/js/pg_tests/run.sh
      - name: Toxi
        run: bash integration/toxi/run.sh
      - name: Python
        run: bash integration/python/run.sh
      - name: Ruby
        run: bash integration/ruby/run.sh
      - name: Java
        run: bash integration/java/run.sh
      - name: More complex stuff
        run: bash integration/complex/run.sh
      - name: Rust
        run: bash integration/rust/run.sh
